/** One-shot layout map: old chapter folder → docs/ path. Not used after migration. */

export const GROUPS = [
  { rel: 'ml', title: '机器学习', order: 10, collapsed: false },
  { rel: 'ml/foundations', title: '基石', order: 10, collapsed: false },
  { rel: 'ml/classic', title: '经典', order: 20, collapsed: false },
  { rel: 'ml/advanced', title: '进阶', order: 30, collapsed: true },
  { rel: 'dl', title: '深度学习', order: 20, collapsed: false },
  { rel: 'cv', title: '计算机视觉', order: 30, collapsed: false },
  { rel: 'nlp', title: '自然语言处理', order: 40, collapsed: false },
  { rel: 'rl', title: '强化学习', order: 50, collapsed: false },
  { rel: 'systems', title: '系统与应用', order: 60, collapsed: false },
  { rel: 'science', title: '科学计算', order: 70, collapsed: true },
  { rel: 'world-models', title: '世界模型', order: 80, collapsed: true },
  { rel: 'algorithms', title: '算法与数据结构', order: 90, collapsed: true },
  { rel: 'algorithms/basics', title: '基础结构', order: 10, collapsed: false },
  { rel: 'algorithms/graph', title: '图', order: 20, collapsed: false },
  { rel: 'algorithms/strategy', title: '策略', order: 30, collapsed: false },
  { rel: 'algorithms/topics', title: '专题', order: 40, collapsed: false },
  { rel: 'papers', title: '论文精读', order: 100, collapsed: true },
]

export const CHAPTERS = [
  { from: 's01_ai_overview', to: 'ml/foundations/ai-overview', title: 's01 AI 全景图', order: 10 },
  { from: 's02_linear_regression', to: 'ml/foundations/linear-regression', title: 's02 线性回归', order: 20 },
  { from: 's03_logistic_regression', to: 'ml/foundations/logistic-regression', title: 's03 逻辑回归', order: 30 },
  { from: 's04_bias_variance', to: 'ml/foundations/bias-variance', title: 's04 过拟合与正则化', order: 40 },

  { from: 'ml01_knn', to: 'ml/classic/knn', title: 'ml01 k-近邻与距离度量', order: 10 },
  { from: 'ml02_bayesian_decision', to: 'ml/classic/bayesian-decision', title: 'ml02 贝叶斯决策理论', order: 20 },
  { from: 'ml03_naive_bayes', to: 'ml/classic/naive-bayes', title: 'ml03 朴素贝叶斯与贝叶斯网络', order: 30 },
  { from: 'ml04_svm', to: 'ml/classic/svm', title: 'ml04 支持向量机 (SVM)', order: 40 },
  { from: 'ml05_decision_tree', to: 'ml/classic/decision-tree', title: 'ml05 决策树', order: 50 },

  { from: 'ml06_random_forest', to: 'ml/advanced/random-forest', title: 'ml06 集成学习：Bagging与随机森林', order: 10 },
  { from: 'ml07_boosting', to: 'ml/advanced/boosting', title: 'ml07 集成学习：Boosting与Stacking', order: 20 },
  { from: 'ml08_clustering', to: 'ml/advanced/clustering', title: 'ml08 聚类：无监督学习的核心', order: 30 },
  { from: 'ml09_dimensionality_reduction', to: 'ml/advanced/dimensionality-reduction', title: 'ml09 降维与特征工程', order: 40 },
  { from: 'ml10_monte_carlo', to: 'ml/advanced/monte-carlo', title: 'ml10 蒙特卡洛方法', order: 50 },
  { from: 'ml11_hmm', to: 'ml/advanced/hmm', title: 'ml11 隐马尔可夫模型 (HMM)', order: 60 },
  { from: 'ml12_em_gmm', to: 'ml/advanced/em-gmm', title: 'ml12 EM算法与高斯混合模型', order: 70 },
  { from: 'ml13_probabilistic_graphical_models', to: 'ml/advanced/probabilistic-graphical-models', title: 'ml13 概率图模型基础', order: 80 },
  { from: 'ml14_kernel_gp', to: 'ml/advanced/kernel-gp', title: 'ml14 核方法与高斯过程', order: 90 },

  { from: 's05_forward_computation_graph', to: 'dl/forward-graph', title: 's05 计算图与前向传播', order: 10 },
  { from: 's06_backprop_chain_rule', to: 'dl/backprop', title: 's06 反向传播与链式法则', order: 20 },
  { from: 's07_matrix_backprop', to: 'dl/matrix-backprop', title: 's07 多层网络矩阵反传', order: 30 },
  { from: 's08_optimizers_sgd_to_adam', to: 'dl/optimizers', title: 's08 优化器：SGD→Adam', order: 40 },
  { from: 's09_adam_deep_dive', to: 'dl/adam', title: 's09 Adam 深度解析', order: 50 },

  { from: 's10_cnn_fundamentals', to: 'cv/cnn', title: 's10 CNN 核心原理', order: 10 },
  { from: 's11_cnn_architectures', to: 'cv/architectures', title: 's11 经典架构演进', order: 20 },
  { from: 's12_object_detection', to: 'cv/object-detection', title: 's12 目标检测', order: 30 },
  { from: 's11b_vit', to: 'cv/vit', title: 's12b Vision Transformer', order: 40 },
  { from: 's13_image_generation', to: 'cv/generation', title: 's13 图像生成', order: 50 },

  { from: 's14_text_representation', to: 'nlp/text-representation', title: 's14 文本表示', order: 10 },
  { from: 's15_sequence_models', to: 'nlp/sequence-models', title: 's15 序列模型', order: 20 },
  { from: 's16_attention_transformer', to: 'nlp/transformer', title: 's16 Attention & Transformer', order: 30 },
  { from: 's17_pretrained_models', to: 'nlp/pretrained', title: 's17 预训练范式', order: 40 },
  { from: 's18_large_language_models', to: 'nlp/llm', title: 's18 大语言模型', order: 50 },

  { from: 's19_rl_qlearning', to: 'rl/qlearning', title: 's19 MDP & Q-Learning', order: 10 },
  { from: 's20_deep_rl', to: 'rl/deep-rl', title: 's20 深度强化学习', order: 20 },
  { from: 's21_rlhf', to: 'rl/rlhf', title: 's21 RLHF', order: 30 },

  { from: 's22_multimodal', to: 'systems/multimodal', title: 's22 多模态模型', order: 10 },
  { from: 's23_rag_agent', to: 'systems/rag-agent', title: 's23 RAG 与 Agent', order: 20 },
  { from: 's24_deployment_inference', to: 'systems/deployment', title: 's24 部署与推理优化', order: 30 },
  { from: 's25_ai_safety', to: 'systems/safety', title: 's25 AI 安全与对齐', order: 40 },

  { from: 'as01_ai4s_overview', to: 'science/overview', title: 'as01 AI4S 全景', order: 10 },
  { from: 'as02_pinn', to: 'science/pinn', title: 'as02 PINN', order: 20 },
  { from: 'as03_fno', to: 'science/fno', title: 'as03 Neural Operator 与 FNO', order: 30 },
  { from: 'as04_pino', to: 'science/pino', title: 'as04 PINO', order: 40 },
  { from: 'as05_gnn_science', to: 'science/gnn', title: 'as05 科学计算中的 GNN', order: 50 },
  { from: 'as06_alphafold', to: 'science/alphafold', title: 'as06 蛋白质结构预测与 AlphaFold', order: 60 },
  { from: 'as07_alphachip_eda', to: 'science/alphachip', title: 'as07 AlphaChip 与电路设计中的神经网络', order: 70 },
  { from: 'as08_ai4s_frontier', to: 'science/frontier', title: 'as08 AI4S 综合与前沿', order: 80 },

  { from: 'wm01_world_model_intro', to: 'world-models/intro', title: 'wm01 世界模型导论与分类', order: 10 },
  { from: 'wm02_planet_rssm', to: 'world-models/rssm', title: 'wm02 经典起源与 RSSM', order: 20 },
  { from: 'wm03_dreamer', to: 'world-models/dreamer', title: 'wm03 Dreamer 家族', order: 30 },
  { from: 'wm04_muzero', to: 'world-models/muzero', title: 'wm04 MuZero：隐式世界模型', order: 40 },
  { from: 'wm05_jepa', to: 'world-models/jepa', title: 'wm05 JEPA / V-JEPA', order: 50 },
  { from: 'wm06_genie', to: 'world-models/genie', title: 'wm06 Genie：交互式世界模型', order: 60 },
  { from: 'wm07_video_world_models', to: 'world-models/video', title: 'wm07 视频生成式世界模型', order: 70 },
  { from: 'wm08_llm_world_model', to: 'world-models/llm', title: 'wm08 LLM 世界模型与路径对比', order: 80 },

  { from: 'algo01_complexity', to: 'algorithms/basics/complexity', title: 'algo01 复杂度分析与渐进记号', order: 10 },
  { from: 'algo02_arrays_linkedlist_hash', to: 'algorithms/basics/arrays-hash', title: 'algo02 数组、链表与哈希表', order: 20 },
  { from: 'algo03_stack_queue', to: 'algorithms/basics/stack-queue', title: 'algo03 栈与队列', order: 30 },
  { from: 'algo04_tree_binarytree', to: 'algorithms/basics/tree', title: 'algo04 树与二叉树', order: 40 },
  { from: 'algo05_heap_unionfind_skiplist', to: 'algorithms/basics/heap-unionfind', title: 'algo05 堆、并查集与跳跃表', order: 50 },
  { from: 'algo06_graph_basics', to: 'algorithms/graph/basics', title: 'algo06 图论基础', order: 10 },
  { from: 'algo07_shortest_path', to: 'algorithms/graph/shortest-path', title: 'algo07 最短路径', order: 20 },
  { from: 'algo08_mst_networkflow', to: 'algorithms/graph/mst-flow', title: 'algo08 最小生成树与网络流', order: 30 },
  { from: 'algo09_greedy', to: 'algorithms/strategy/greedy', title: 'algo09 贪心算法', order: 10 },
  { from: 'algo10_divide_conquer', to: 'algorithms/strategy/divide-conquer', title: 'algo10 递归、分治与二分', order: 20 },
  { from: 'algo11_dp_1', to: 'algorithms/strategy/dp-1', title: 'algo11 动态规划（上）', order: 30 },
  { from: 'algo12_dp_2', to: 'algorithms/strategy/dp-2', title: 'algo12 动态规划（下）', order: 40 },
  { from: 'algo13_string', to: 'algorithms/topics/string', title: 'algo13 字符串算法', order: 10 },
  { from: 'algo14_segment_tree', to: 'algorithms/topics/segment-tree', title: 'algo14 线段树与树状数组', order: 20 },
  { from: 'algo15_number_theory', to: 'algorithms/topics/number-theory', title: 'algo15 数论与组合数学', order: 30 },
  { from: 'algo16_geometry_game', to: 'algorithms/topics/geometry-game', title: 'algo16 计算几何与博弈论入门', order: 40 },

  { from: 'paper00_placeholder', to: 'papers/placeholder', title: 'paper00 占位：经典论文讲解即将更新', order: 10 },
]
